### ISSUE TITLE
タイトルが日本語の時、サイドバーで直下のページが表示されない

### ISSUE THREAD

**Issue by mazrean** [traPtitech/crowi#2]
例:https://wiki.trap.jp/Event/welcome/20/%E8%A8%88%E7%94%BB

**Comment by mazrean** [comment]
この時、/page.listを叩いたレスポンスが空の配列になっているので、投げる値が間違っているか検索がおかしいかのどちらか。
URLエンコードが関係していそう。

**Comment by sapphi-red** [comment]
https://wiki.trap.jp/_api/pages.list?path=%2FEvent%2Fwelcome%2F20%2F%25E8%25A8%2588%25E7%2594%25BB&offset=0

https://wiki.trap.jp/_api/pages.list?path=%2FEvent%2Fwelcome%2F20%2F%E8%A8%88%E7%94%BB&offset=0

上記ではとれなくて下記でとれるので`%25E8%25A8%2588%25E7%2594%25BB`だとダメで`%E8%A8%88%E7%94%BB`だととれる
前者は二回URIEncodeが走ってる(`%`=>`%25`)

なのでAPI叩く前にdecodeURIComponentすれば直る
