### ISSUE TITLE
ログイン認証後のリダイレクトで必ずトップページに飛ぶ

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/crowi#4]
行きたかったページにリダイレクトされてほしい

**Comment by sapphi-red** [comment]
middleware化しないとだめ

**Comment by sapphi-red** [comment]
passport対応してるしそれ使ったほうが速い気がする

**Comment by mazrean** [comment]
リダイレクトがトップページに飛ぶのはcontinueというクエリパラメーターを読んでいなかったためだったから、読むようにして暫定的に解決した。
現在middleware化中。
