### ISSUE TITLE
headがうまく飛ばない

### ISSUE THREAD

**Issue by mazrean** [traPtitech/crowi#7]
#head~でその位置に飛ぶはずだが、うまく飛ばない
例) https://wiki.trap.jp/dictionary#head263

**Comment by mazrean** [comment]
traQでのログインをmiddlewareに挟んだことが影響していそう？

**Comment by sapphi-red** [comment]
原因はマークダウンのレンダリングがページロード後なのでそのヘッダーが実際にDOMに存在するのはそのあとのため
なので、元々動いていないし動くはずがない

直すにはレンダリング後に`location.hash`を読んで`getElementById`してそれを`element.scrollInto`すればよいはず
